GET http://localhost:3032/
###
POST http://localhost:3032/signup
Content-Type: application/json

{
    "typeOfReg":"jobseeker",
    "fullname":"munikumar",
    "email":"munikumar@gmail.com",
    "password":"Muni@123",
    "mobileNum":9562541254,
    "gender":"Male"
 
     
}