GET http://localhost:4005/
###
POST http://localhost:4005/signup
Content-Type: application/json

{
    "typeOfRegistration":"Jobseeker",
    "fullname":"Sri",
    "email":"sri@gmail.com",
    "password":"sri@123",
    "mobileNumber":9658451245,
    "gender":"Male"
 
     
}
###
GET http://localhost:4005/allusers
###
GET http://localhost:4005/user/64be038d864e273d03c76073
###
PUT  http://localhost:4005/user/64be038d864e273d03c76073
Content-Type: application/json

{
    
    "fullname":"srikanth",
    "mobileNumber":9658451245,
}

###
DELETE http://localhost:4005/user/64be55d5e2e6fca627f6b077